version: '3.8'

services:
  app:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/cv_files:/app/cv_files
      - ./Backend/.env:/app/.env
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/cv_filter_db
      UPLOAD_FOLDER: /app/cv_files

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
